Créer une class StandardScaler avec comme méthode fit, transform, fit_transform et en attribut un dicitonnaire params_ qui contient la moyenne et l'écart_type de vos données. Les données en entrées sont uniquement de array numpy (pas des dataframes)
me dire que vous avez terminé avant de faire le bonus.
en bonus :
- mettre une erreur si on essaye de transform sans avoir de fit
- permettre au code de fonctionner, peu importe si l'entrée est une numpy array ou une dataframe

[Source](https://kenzotakahashi.github.io/scikit-learns-useful-tools-from-scratch.html)

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

data = np.random.random(20)
data

array([0.73847004, 0.5436615 , 0.30826534, 0.18544405, 0.31435656,
       0.29432614, 0.44531876, 0.83904645, 0.27470113, 0.06727461,
       0.77626171, 0.67007503, 0.88938458, 0.9857929 , 0.56091397,
       0.58249368, 0.65020791, 0.72321018, 0.5983583 , 0.82115925])

In [5]:
params_ = {}
class StandardScaler(object):
    def __init__(self, params_):
        self.params_ = {}

    def fit(self, X):
        self.mean_ = np.mean(X, axis=0)
        self.scale_ = np.std(X - self.mean_, axis=0)
        self.params_.update({"mean": self.mean_, "scale": self.scale_})
        return self

    def transform(self, X):
        return (X - self.mean_) / self.scale_

    def fit_transform(self, X):
        return self.fit(X).transform(X)

scaler = StandardScaler(params_)
scaler.fit_transform(data)

array([ 0.70428995, -0.07956775, -1.0267392 , -1.5209394 , -1.00222975,
       -1.08282682, -0.47527276,  1.10898264, -1.16179266, -1.99642173,
        0.85635355,  0.42908666,  1.31152987,  1.69945129, -0.0101484 ,
        0.07668259,  0.34914664,  0.64288835,  0.14051762,  1.03700932])

In [7]:
df = pd.read_csv('vine.csv')
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [8]:
params_ = {}
class StandardScaler(object):
    def __init__(self, params_):
        self.params_ = {}

    def fit(self, X):
        self.mean_ = np.mean(X, axis=0)
        self.scale_ = np.std(X - self.mean_, axis=0)
        self.params_.update({"mean": self.mean_, "scale": self.scale_})
        return self

    def transform(self, X):
        return (X - self.mean_) / self.scale_

    def fit_transform(self, X):
        return self.fit(X).transform(X)

scaler = StandardScaler(params_)
scaler.fit_transform(df)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246,-0.787823
1,-0.298547,1.967442,-1.391472,0.043416,0.223875,0.872638,0.624363,0.028261,-0.719933,0.128950,-0.584777,-0.787823
2,-0.298547,1.297065,-1.186070,-0.169427,0.096353,-0.083669,0.229047,0.134264,-0.331177,-0.048089,-0.584777,-0.787823
3,1.654856,-1.384443,1.484154,-0.453218,-0.264960,0.107592,0.411500,0.664277,-0.979104,-0.461180,-0.584777,0.450848
4,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246,-0.787823
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,-1.217796,0.403229,-0.980669,-0.382271,0.053845,1.542054,-0.075043,-0.978765,0.899886,-0.461180,0.072294,-0.787823
1595,-1.390155,0.123905,-0.877968,-0.240375,-0.541259,2.211469,0.137820,-0.862162,1.353436,0.601055,0.729364,0.450848
1596,-1.160343,-0.099554,-0.723916,-0.169427,-0.243707,1.255161,-0.196679,-0.533554,0.705508,0.542042,0.541630,0.450848
1597,-1.390155,0.654620,-0.775267,-0.382271,-0.264960,1.542054,-0.075043,-0.676657,1.677400,0.305990,-0.209308,-0.787823
1598,-1.332702,-1.216849,1.021999,0.752894,-0.434990,0.203223,-0.135861,-0.666057,0.511130,0.010924,0.541630,0.450848